spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 100000MB
      max-request-size: 1000000MB

